// Generated by ts-to-zod
import { z } from "zod";

export const repositorySchema = z.object({
  spec: z.object({
    owner: z.string().min(1).max(20),
    repo: z.string().min(1).max(20),
  }),
  body: z.object({
    tags: z.array(z.string()).min(1).max(10),
  }),
  meta: z.object({
    created_at: z.date(),
    updated_at: z.date(),
  }),
  query: z.object({
    since: z.date().optional(),
    until: z.date().optional(),
  }),
});
