name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    env:
      account_id: ${{ secrets.ACCOUNT_ID }}
      api_token: ${{ secrets.API_TOKEN }}

    if: ${{ env.account_id != '' && env.api_token != '' }} 

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Denoflare
        run: >
          deno install --unstable --allow-read --allow-net --allow-env --allow-run --name denoflare --force 
          https://raw.githubusercontent.com/skymethod/denoflare/v0.5.2/cli/cli.ts

      - name: Deploy
        run: >
          denoflare push ${{ github.repository }}
          --account-id ${{ secrets.ACCOUNT_ID }}
          --api-token ${{ secrets.API_TOKEN }}
