name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Install ghlog
        run: deno install -A https://pax.deno.dev/hasundue/ghlog/ghlog.ts 

      - name: Generate Release Notes
        run: ghlog ${{ github.repository }} -s | xargs -I {tag} echo "NEW_TAG={tag}" >> $GITHUB_ENV

      - name: Release
        if: ${{ env.NEW_TAG != 'UNRELEASED' }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.NEW_TAG }}'
          name: '${{ env.NEW_TAG }}'
          bodyFile: 'CHANGELOG.md'
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
