name: Release

on:
  push:
    branches: [ main ]

env:
  account_id: ${{ secrets.ACCOUNT_ID }}
  api_token: ${{ secrets.API_TOKEN }}

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install ghlog
        run: deno install -A https://pax.deno.dev/hasundue/ghlog/ghlog.ts 

      - name: Generate Release Notes
        run: ghlog ${{ github.repository }} -s | xargs -I {tag} echo "NEW_TAG={tag}" >> $GITHUB_ENV

      - name: Release
        id: release
        if: ${{ env.NEW_TAG != 'UNRELEASED' }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ env.NEW_TAG }}'
          name: '${{ env.NEW_TAG }}'
          bodyFile: 'CHANGELOG.md'
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Denoflare
        id: denoflare
        if: ${{ steps.release.conclusion == 'success' && env.account_id != '' && env.api_token != '' }} 
        run: >
          deno install --unstable --allow-read --allow-net --allow-env --allow-run --name denoflare --force 
          https://raw.githubusercontent.com/skymethod/denoflare/v0.5.2/cli/cli.ts

      - name: Deploy Demo
        if: ${{ steps.denoflare.conclusion == 'success' }}
        run: >
          denoflare push flash-demo
          --account-id ${{ secrets.ACCOUNT_ID }}
          --api-token ${{ secrets.API_TOKEN }}
